root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bin/api ./cmd/api"
entrypoint = ["./tmp/bin/api"]
include_ext = ["go", "yaml", "yml", "toml"]
exclude_dir = ["tmp", "vendor"]
delay = 200
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true
